### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by pgstevenson** [lenz99-/lme4cens#1] opened 2019-10-04 06:37 UTC
Hi there,

I just found a poster on this package when looking for methods for censored linear mixed effects regression. It looks like this package will help me with my client's research question.

I tried installing your package with

`remotes::install_github("https://github.com/lenz99-/lme4cens")`

But got the following error:

> Error: package or namespace load failed for 'lme4cens' in namespaceExport(ns, exports):
>  undefined exports: lmsegm, lmsegm.objFun
> Error: loading failed

```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8.1 x64 (build 9600)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252   
[3] LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
[5] LC_TIME=English_Australia.1252    

attached base packages:
[1] graphics  grDevices utils     datasets  stats     methods   base     

other attached packages:
 [1] repmis_0.5            ProjectTemplate_0.9.0 lubridate_1.7.4       forcats_0.4.0        
 [5] stringr_1.4.0         dplyr_0.8.3           purrr_0.3.2           readr_1.3.1          
 [9] tidyr_1.0.0           tibble_2.1.3          ggplot2_3.2.1         tidyverse_1.2.1      
[13] plyr_1.8.4            reshape2_1.4.3       

loaded via a namespace (and not attached):
 [1] tidyselect_0.2.5  remotes_2.1.0     haven_2.1.1       lattice_0.20-38   colorspace_1.4-1 
 [6] vctrs_0.2.0       generics_0.0.2    pkgbuild_1.0.5    rlang_0.4.0       R.oo_1.22.0      
[11] pillar_1.4.2      glue_1.3.1        withr_2.1.2       R.utils_2.9.0     modelr_0.1.5     
[16] readxl_1.3.1      lifecycle_0.1.0   R.cache_0.13.0    munsell_0.5.0     gtable_0.3.0     
[21] cellranger_1.1.0  rvest_0.3.4       R.methodsS3_1.7.1 callr_3.3.2       ps_1.3.0         
[26] curl_4.2          broom_0.5.2       Rcpp_1.0.2        scales_1.0.0      backports_1.1.5  
[31] jsonlite_1.6      hms_0.5.1         digest_0.6.21     packrat_0.5.0     stringi_1.4.3    
[36] processx_3.4.1    rprojroot_1.3-2   grid_3.6.1        cli_1.1.0         tools_3.6.1      
[41] magrittr_1.5      lazyeval_0.2.2    crayon_1.3.4      pkgconfig_2.0.3   zeallot_0.1.0    
[46] prettyunits_1.0.2 data.table_1.12.2 xml2_1.2.2        assertthat_0.2.1  httr_1.4.1       
[51] rstudioapi_0.10   R6_2.4.0          nlme_3.1-141      compiler_3.6.1   
```

**Comment by lenz99-** [comment] 2019-10-04 14:40
Thanks for reporting this issue which I can confirm.
I introduced two wrong exports  in the package which make it fail during installation.

It should be fixed with the current version,
`remotes::install_github("lenz99-/lme4cens")` works for me (although not tested on Windows).

**Closed by lenz99-** 2019-10-04 14:40 UTC
